### ISSUE TITLE
Do you have an example of monero's full transfer here

### ISSUE THREAD

**Issue by vae520283995** [edwinhere/nazgul#1]

**Comment by edwinhere** [comment]
Sorry for the late response.

I don't have an example for a monero transfer. Monero uses 32-byte hashes. This library uses 64-byte hashes. To achieve monero-like transactions you need (in addition to 32-byte hashes) to use bulletproofs, one-time addresses. Monero also uses a different elliptic curve than this library.

This library is intended to be used for non-monero projects which like to leverage the same primitives monero invented.

For example, if you want to an e-voting system, or e-company-seal, all you need is this library. It can also do monero-like currencies, but you need more pieces to get that working like bulletproofs and one-time-addresses.

I am planning to write those when I get some time. I don't want to replicate monero functionality. Instead I want to expose the same primitives for enabling similar projects.

**Comment by vae520283995** [comment]
> Sorry for the late response.
> 
> I don't have an example for a monero transfer. Monero uses 32-byte hashes. This library uses 64-byte hashes. To achieve monero-like transactions you need (in addition to 32-byte hashes) to use bulletproofs, one-time addresses. Monero also uses a different elliptic curve than this library.
> 
> This library is intended to be used for non-monero projects which like to leverage the same primitives monero invented.
> 
> For example, if you want to an e-voting system, or e-company-seal, all you need is this library. It can also do monero-like currencies, but you need more pieces to get that working like bulletproofs and one-time-addresses.
> 
> I am planning to write those when I get some time. I don't want to replicate monero functionality. Instead I want to expose the same primitives for enabling similar projects.

That's a pity
