### ISSUE TITLE
CLSAG sign/verify time quadratic to the ring size

### ISSUE THREAD

**Issue by witolyu** [edwinhere/nazgul#2]
Hi~

We notice from our experiment on CLSAG that the sign/verify time is quadratic to ring size. We have tested ring size up to 2500. However, by looking at page 22 of https://eprint.iacr.org/2019/654.pdf, we suspect it shouldn't be that high (the previous MLSAG scheme is of linear signing cost).

We run some test and realize the quadratic cost comes from the following lines of codes:
Sign:
line 146-158

Verify:
line 273-280

It is quite strange as each iteration of the outer loop runs the exact same codes and we wonder whether it could be optimized.

**Comment by edwinhere** [comment]
Sorry for the late reply.

Even in MLSAG, the time complexity is `n · m` keys (`n` is the ring size, `m` is the number of signing keys). See this outer loop [here](https://github.com/edwinhere/nazgul/blob/master/src/mlsag.rs#L116). That loop only terminates based on how many rows there are i.e. `nr` which is the ring size.

I don't think it can be optimized to improve time complexity. But certainly the code can be refactored to increase code reuse.
